package model;

public abstract class Encodable {

    /**The header of the encodable class. Its usage is optional**/
    public final String header;


    protected Encodable(String header) {
        this.header = header;
    }

    protected Encodable() {
        this.header = "";
    }


    /**
     * Check if this dataLine was generated by the generateDataLine methode and thus is decodable
     *
     * @param encodedDataLine the unknown data line
     * @return true if it is decodable else false
     */
    public abstract boolean recogniseDataLine(String encodedDataLine);

    /**
     * Return the string defining the class in the wanted file
     * @return
     */
    public abstract String generateDataLine();

    /**
     * Decode the encoded data to fill the class data
     *
     * @param encodedDataLine
     */
    protected abstract void decodeDataLine(String encodedDataLine);
}
